<a href="https://colab.research.google.com/github/KedarSJadhav/MSC_Sem-1_FDS/blob/main/Chapter_7_Data_Cleaning_and_Preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Data Cleaning and Preparation**

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [4]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [5]:
string_data[0] = None

In [6]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

**Filtering Out Missing Data**

In [7]:
from numpy import nan as NA

In [8]:
data = pd.Series([1, NA, 3.5, NA, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [9]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [10]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],
                     [NA, NA, NA], [NA, 6.5, 3.]])

In [11]:
cleaned = data.dropna()

In [12]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [13]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [14]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [15]:
data[4] = NA

In [16]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [17]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [18]:
df = pd.DataFrame(np.random.randn(7, 3))

In [19]:
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA

In [20]:
df

0         1         2
0  0.985534       NaN       NaN
1  1.607883       NaN       NaN
2 -0.633885       NaN -0.694927
3 -0.730259       NaN  0.403105
4  1.610959 -0.845811 -0.941338
5  0.854182  0.029848 -0.035191
6 -0.220268 -1.533293  0.384810

In [21]:
df.dropna()

0         1         2
4  1.610959 -0.845811 -0.941338
5  0.854182  0.029848 -0.035191
6 -0.220268 -1.533293  0.384810

In [22]:
df.dropna(thresh=2)

0         1         2
2 -0.633885       NaN -0.694927
3 -0.730259       NaN  0.403105
4  1.610959 -0.845811 -0.941338
5  0.854182  0.029848 -0.035191
6 -0.220268 -1.533293  0.384810

**Filling In Missing Data**

In [23]:
df.fillna(0)

0         1         2
0  0.985534  0.000000  0.000000
1  1.607883  0.000000  0.000000
2 -0.633885  0.000000 -0.694927
3 -0.730259  0.000000  0.403105
4  1.610959 -0.845811 -0.941338
5  0.854182  0.029848 -0.035191
6 -0.220268 -1.533293  0.384810

In [24]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0  0.985534  0.500000  0.000000
1  1.607883  0.500000  0.000000
2 -0.633885  0.500000 -0.694927
3 -0.730259  0.500000  0.403105
4  1.610959 -0.845811 -0.941338
5  0.854182  0.029848 -0.035191
6 -0.220268 -1.533293  0.384810

In [25]:
_ = df.fillna(0, inplace=True)
df

0         1         2
0  0.985534  0.000000  0.000000
1  1.607883  0.000000  0.000000
2 -0.633885  0.000000 -0.694927
3 -0.730259  0.000000  0.403105
4  1.610959 -0.845811 -0.941338
5  0.854182  0.029848 -0.035191
6 -0.220268 -1.533293  0.384810

In [26]:
df = pd.DataFrame(np.random.randn(6, 3))

In [27]:
df.iloc[2:, 1] = NA
df.iloc[4:, 2] = NA

In [28]:
df

0         1         2
0 -0.957082 -1.123857 -0.388694
1  0.159299 -1.006275 -1.426772
2 -0.405162       NaN -1.166084
3 -0.742619       NaN -1.921052
4 -0.423089       NaN       NaN
5  1.655697       NaN       NaN

In [29]:
df.fillna(method='ffill')

0         1         2
0 -0.957082 -1.123857 -0.388694
1  0.159299 -1.006275 -1.426772
2 -0.405162 -1.006275 -1.166084
3 -0.742619 -1.006275 -1.921052
4 -0.423089 -1.006275 -1.921052
5  1.655697 -1.006275 -1.921052

In [30]:
df.fillna(method='ffill', limit=2)

0         1         2
0 -0.957082 -1.123857 -0.388694
1  0.159299 -1.006275 -1.426772
2 -0.405162 -1.006275 -1.166084
3 -0.742619 -1.006275 -1.921052
4 -0.423089       NaN -1.921052
5  1.655697       NaN -1.921052

In [31]:
data = pd.Series([1., NA, 3.5, NA, 7])

In [32]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [33]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

**Data Transformation**

**  Removing Duplicates**

In [34]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})

In [35]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [36]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [37]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [38]:
data['v1'] = range(7)

In [39]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [40]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

**Transforming Data Using a Function or Mapping**

In [41]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
                              'Pastrami', 'corned beef', 'Bacon',
                              'pastrami', 'honey ham', 'nova lox'],
                     'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [42]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [43]:
meat_to_animal = {
  'bacon': 'pig',
  'pulled pork': 'pig',
  'pastrami': 'cow',
  'corned beef': 'cow',
  'honey ham': 'pig',
  'nova lox': 'salmon'
}

In [44]:
lowercased = data['food'].str.lower()

In [45]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [46]:
data['animal'] = lowercased.map(meat_to_animal)

In [47]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [48]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

**Replacing Values**

In [49]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [50]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [51]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [52]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [53]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [54]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [55]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [56]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [57]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [58]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

**Renaming Axis Indexes**

In [59]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [60]:
transform = lambda x: x[:4].upper()

In [61]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [62]:
data.index = data.index.map(transform)

In [63]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [64]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [65]:
data.rename(index={'OHIO': 'INDIANA'},
            columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [66]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)

In [67]:
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

**Discretization and Binning**

In [68]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [69]:
bins = [18, 25, 35, 60, 100]

In [70]:
cats = pd.cut(ages, bins)

In [71]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [72]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [73]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [74]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [75]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [76]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

In [77]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [78]:
data = np.random.rand(20)

In [79]:
pd.cut(data, 4, precision=2)

[(0.73, 0.97], (0.73, 0.97], (0.73, 0.97], (0.73, 0.97], (0.03, 0.27], ..., (0.73, 0.97], (0.03, 0.27], (0.03, 0.27], (0.73, 0.97], (0.27, 0.5]]
Length: 20
Categories (4, interval[float64]): [(0.03, 0.27] < (0.27, 0.5] < (0.5, 0.73] < (0.73, 0.97]]

In [80]:
data = np.random.randn(1000)

In [81]:
cats = pd.qcut(data, 4)

In [82]:
cats

[(-0.787, -0.085], (-0.787, -0.085], (-0.085, 0.61], (-0.085, 0.61], (-0.085, 0.61], ..., (-0.787, -0.085], (-0.085, 0.61], (0.61, 2.683], (-3.562, -0.787], (-0.085, 0.61]]
Length: 1000
Categories (4, interval[float64]): [(-3.562, -0.787] < (-0.787, -0.085] < (-0.085, 0.61] <
                                    (0.61, 2.683]]

In [83]:
pd.value_counts(cats)

(0.61, 2.683]       250
(-0.085, 0.61]      250
(-0.787, -0.085]    250
(-3.562, -0.787]    250
dtype: int64

In [85]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(-1.261, -0.085], (-1.261, -0.085], (-0.085, 1.199], (-0.085, 1.199], (-0.085, 1.199], ..., (-1.261, -0.085], (-0.085, 1.199], (1.199, 2.683], (-1.261, -0.085], (-0.085, 1.199]]
Length: 1000
Categories (4, interval[float64]): [(-3.562, -1.261] < (-1.261, -0.085] < (-0.085, 1.199] <
                                    (1.199, 2.683]]

**Detecting and Filtering Outliers**

In [86]:
data = pd.DataFrame(np.random.randn(1000, 4))

In [87]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.029621    -0.001549     0.021282     0.003878
std       1.011882     0.977621     0.974211     1.008105
min      -3.448232    -3.427269    -3.130771    -3.645705
25%      -0.640691    -0.660488    -0.636756    -0.679565
50%      -0.006075     0.005448    -0.010515    -0.026499
75%       0.739682     0.689226     0.637308     0.691489
max       3.075103     3.198433     2.993605     3.288643

In [88]:
col = data[2]

In [89]:
col[np.abs(col) > 3]

506   -3.130771
Name: 2, dtype: float64

In [90]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
93  -0.020159 -2.319529 -0.450054  3.279943
100  1.014487 -3.427269 -0.303843  0.999958
279 -0.984423  3.198433 -0.739687  1.455664
415 -3.303352  0.841328  0.044512 -0.478958
497  0.132805  3.088547 -0.897779 -0.029461
506 -0.875547  0.658718 -3.130771 -0.769665
526 -0.571419  3.012912  0.976927 -0.949221
571 -1.899461  0.273812  0.055502  3.288643
577  3.075103  0.256502 -0.462468 -0.284606
680  0.583763 -0.271493 -0.738533 -3.645705
722 -3.448232  0.271836 -0.642194  2.056039
734  0.921635  3.046727 -1.484464 -0.665019

In [91]:
data[np.abs(data) > 3] = np.sign(data) * 3

In [92]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.030297    -0.001468     0.021413     0.003955
std       1.009257     0.975121     0.973797     1.004193
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.640691    -0.660488    -0.636756    -0.679565
50%      -0.006075     0.005448    -0.010515    -0.026499
75%       0.739682     0.689226     0.637308     0.691489
max       3.000000     3.000000     2.993605     3.000000

In [93]:
np.sign(data).head()

0    1    2    3
0  1.0 -1.0  1.0 -1.0
1 -1.0 -1.0 -1.0  1.0
2  1.0 -1.0  1.0  1.0
3  1.0 -1.0  1.0  1.0
4 -1.0  1.0  1.0  1.0

**Permutation and Random Sampling**

In [94]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))

In [95]:
sampler = np.random.permutation(5)

In [96]:
sampler

array([3, 1, 0, 2, 4])

In [97]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [98]:
df.take(sampler)

0   1   2   3
3  12  13  14  15
1   4   5   6   7
0   0   1   2   3
2   8   9  10  11
4  16  17  18  19

In [99]:
df.sample(n=3)

0  1   2   3
1  4  5   6   7
0  0  1   2   3
2  8  9  10  11

In [100]:
choices = pd.Series([5, 7, -1, 6, 4])

In [101]:
choices

0    5
1    7
2   -1
3    6
4    4
dtype: int64

In [102]:
draws = choices.sample(n=10, replace=True)

In [103]:
draws

4    4
4    4
2   -1
4    4
3    6
0    5
2   -1
3    6
2   -1
1    7
dtype: int64

**Computing Indicator/Dummy Variables**

In [104]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                   'data1': range(6)})

In [105]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [106]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [107]:
dummies = pd.get_dummies(df['key'], prefix='key')

In [108]:
dummies

key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [109]:
df_with_dummy = df[['data1']].join(dummies)

In [110]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [111]:
mnames = ['movie_id', 'title', 'genres']

In [112]:
mnames

['movie_id', 'title', 'genres']

In [114]:
movies = pd.read_table('/content/sample_data/movies.dat', sep='::',
                       header=None, names=mnames)

/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py:767: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return read_csv(**locals())


In [115]:
movies

movie_id  ...                        genres
0            1  ...   Animation|Children's|Comedy
1            2  ...  Adventure|Children's|Fantasy
2            3  ...                Comedy|Romance
3            4  ...                  Comedy|Drama
4            5  ...                        Comedy
...        ...  ...                           ...
3878      3948  ...                        Comedy
3879      3949  ...                         Drama
3880      3950  ...                         Drama
3881      3951  ...                         Drama
3882      3952  ...                Drama|Thriller

[3883 rows x 3 columns]

In [116]:
all_genres = []

In [117]:
for x in movies.genres:
    all_genres.extend(x.split('|'))

In [118]:
genres = pd.unique(all_genres)

In [119]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [120]:
zero_matrix = np.zeros((len(movies), len(genres)))

In [121]:
zero_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [122]:
dummies = pd.DataFrame(zero_matrix, columns=genres)

In [123]:
dummies

Animation  Children's  Comedy  ...  Mystery  Film-Noir  Western
0           0.0         0.0     0.0  ...      0.0        0.0      0.0
1           0.0         0.0     0.0  ...      0.0        0.0      0.0
2           0.0         0.0     0.0  ...      0.0        0.0      0.0
3           0.0         0.0     0.0  ...      0.0        0.0      0.0
4           0.0         0.0     0.0  ...      0.0        0.0      0.0
...         ...         ...     ...  ...      ...        ...      ...
3878        0.0         0.0     0.0  ...      0.0        0.0      0.0
3879        0.0         0.0     0.0  ...      0.0        0.0      0.0
3880        0.0         0.0     0.0  ...      0.0        0.0      0.0
3881        0.0         0.0     0.0  ...      0.0        0.0      0.0
3882        0.0         0.0     0.0  ...      0.0        0.0      0.0

[3883 rows x 18 columns]

In [124]:
gen = movies.genres[0]

In [125]:
gen.split('|')

['Animation', "Children's", 'Comedy']

In [126]:
gen

"Animation|Children's|Comedy"

In [127]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2])

In [128]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1

In [129]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

In [130]:
movies_windic

movie_id  ... Genre_Western
0            1  ...           0.0
1            2  ...           0.0
2            3  ...           0.0
3            4  ...           0.0
4            5  ...           0.0
...        ...  ...           ...
3878      3948  ...           0.0
3879      3949  ...           0.0
3880      3950  ...           0.0
3881      3951  ...           0.0
3882      3952  ...           0.0

[3883 rows x 21 columns]

In [131]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Adventure                                0
Genre_Fantasy                                  0
Genre_Romance                                  0
Genre_Drama                                    0
Genre_Action                                   0
Genre_Crime                                    0
Genre_Thriller                                 0
Genre_Horror                                   0
Genre_Sci-Fi                                   0
Genre_Documentary                              0
Genre_War                                      0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Film-Noir                                0
Genre_Western       

In [132]:
np.random.seed(12345)

In [133]:
values = np.random.rand(10)

In [134]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [135]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [136]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

**String Manipulation**

**String Object Methods**

In [137]:
val = 'a,b,  guido'

In [138]:
val.split(',')

['a', 'b', '  guido']

In [140]:
pieces = [x.strip() for x in val.split(',')]

In [141]:
pieces

['a', 'b', 'guido']

In [142]:
first, second, third = pieces

In [143]:
first + '::' + second + '::' + third

'a::b::guido'

In [144]:
'::'.join(pieces)

'a::b::guido'

In [145]:
'guido' in val

True

In [146]:
val.index(',')

1

In [147]:
val.find(':')

-1

In [149]:
val.count(',')

2

In [150]:
val.replace(',', '::')

'a::b::  guido'

In [151]:
val

'a,b,  guido'

In [152]:
val.replace(',', '')

'ab  guido'

**Regular Expressions**

In [153]:
import re

In [154]:
text = "foo    bar\t baz  \tqux"

In [155]:
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [158]:
regex = re.compile('\s+')

In [159]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [160]:
regex.findall(text)

['    ', '\t ', '  \t']

In [161]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""

In [162]:
text

'Dave dave@google.com\nSteve steve@gmail.com\nRob rob@gmail.com\nRyan ryan@yahoo.com\n'

In [163]:
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

In [164]:
regex = re.compile(pattern, flags=re.IGNORECASE)
# re.IGNORECASE makes the regex case-insensitive

In [165]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [166]:
m = regex.search(text)

In [167]:
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [168]:
text[m.start():m.end()]

'dave@google.com'

In [169]:
print(regex.match(text))

None


In [170]:
print(regex.sub('REDACTED', text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED



In [171]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'

In [172]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [173]:
m = regex.match('wesm@bright.net')

In [174]:
m

<re.Match object; span=(0, 15), match='wesm@bright.net'>

In [175]:
m.groups()

('wesm', 'bright', 'net')

In [176]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [177]:
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3', text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com



**Vectorized String Functions in pandas**

In [178]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com',
        'Rob': 'rob@gmail.com', 'Wes': np.nan}

In [179]:
data = pd.Series(data)

In [180]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [181]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [182]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [183]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [184]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [185]:
matches = data.str.match(pattern, flags=re.IGNORECASE)

In [186]:
matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [188]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [190]:
PREVIOUS_MAX_ROWS = pd.options.display.max_rows

In [191]:
pd.options.display.max_rows = PREVIOUS_MAX_ROWS

In [192]:
PREVIOUS_MAX_ROWS

60