<a href="https://colab.research.google.com/github/KedarSJadhav/MSC_Sem-1_FDS/blob/main/FDS_Lab_2_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
list1=[]

In [ ]:
#Empty list
list1

[]

In [ ]:
type(list1)

list

In [ ]:
#Add value 0-9
list2 = list(range(10))

In [ ]:
list2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
list3 = [str(c) for c in list2]

In [ ]:
list3

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

**List with mix data type**

In [ ]:
list4 = [1,1.23,'c','Aman',True]

In [ ]:
list4

[1, 1.23, 'c', 'Aman', True]

In [ ]:
type(list4)

list

In [ ]:
#Display Data type of each elements in list
[type(item) for item in list4]

[int, float, str, str, bool]

In [ ]:
#Paython array
import array as ar
L= list(range(10))
A= ar.array('i',L)
A
#i represent contents are integer

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#numpy array
import numpy as np
#integer array
np.array([3,2,1,4])

array([3, 2, 1, 4])

In [ ]:
#Automatic/implicit conversion of values/elements
np.array([10.1,4,3,5])

array([10.1,  4. ,  3. ,  5. ])

In [ ]:
#Explicitly specify the data types of array
np.array([1,2,3,4],dtype= 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
#Multi dimensional array with nested list
#[[, ,], [, ,], [, ,]]
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
#Create a length-10 interger array filled with zerO
np.zeros(10, dtype =int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Create two dimensioanl filled with zerO with Float data types
np.zeros((2,5), dtype =float)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#Create 3*5 array filled with value 3.14
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
#Linear sequence
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.arange(0,40,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39])

In [ ]:
#0-2 = 4 elements (0.0, 0.66, 1.33, 2.0)
#Creation of array of evenly spaced value for given range
np.linspace(0,2,4)

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [ ]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
#Create 3*3 array uniformly distrubuted
#random value between (0,1)
np.random.random((3,4))

array([[0.57719088, 0.64784526, 0.34081539, 0.7382354 ],
       [0.49855259, 0.64773421, 0.18503062, 0.8003241 ],
       [0.2544468 , 0.08497436, 0.6049854 , 0.40896779]])

In [ ]:
#Create 3*3 array uniformly distrubuted
#with mean 0 and standard deviation 1
np.random.normal(0,1,(3,3))

array([[ 0.32859695,  1.25961338, -1.53921177],
       [-1.19417386, -0.45089508, -1.98928765],
       [ 0.86853288,  1.37499446,  0.79757441]])

In [ ]:
#Create a 3*3 array of random integer in the of interval(0,10)
np.random.randint(0,10, (3,3))

array([[6, 0, 8],
       [5, 2, 1],
       [4, 2, 9]])

In [ ]:
#Create 3*3 indentity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#create an uninitialized array with 3 elements
np.empty(3)

array([1., 1., 1.])

In [ ]:
np.random.seed(0) # seed for reproducibity

x1=np.random.randint(10, size=6) #one dimensional array
x1

array([5, 0, 3, 3, 7, 9])

In [ ]:
# Seed 100  200   5 6 7
np.random.seed(100)
x2=np.random.randint(200, size=(5,6,7)) #one dimensional array
x2

array([[[  8,  24,  67, 103,  87,  79, 176],
        [138,  94, 180,  98,  53,  66,  14],
        [ 34,  24, 143, 107,  60,  58, 144],
        [137,  93,  86, 130, 155, 108, 132],
        [159, 129, 141, 100,   4,  91, 187],
        [ 67, 135,  49, 175, 193,  61,  14]],

       [[183, 199,  80,   2, 121, 105, 147],
        [ 63, 181,  27,  56, 113, 158, 176],
        [ 47, 167, 109,  38, 172,  18, 192],
        [184, 162, 181,  17,  72,  13, 106],
        [ 30,  17,  53,  68, 178,  91, 181],
        [ 78,   0,  13, 185, 106, 131,  70]],

       [[131, 138, 188, 131, 105, 176, 180],
        [ 43,  36,   5,  71,  38,  94, 170],
        [ 84,  95, 114, 119,  76,  33,  58],
        [102, 170, 150,   0, 183, 147,  53],
        [196, 190,  50, 196, 163, 151,   9],
        [176,  21, 153, 182,   6, 165, 102]],

       [[122, 116, 186,  39, 107,  51,  30],
        [121,  66, 152, 183,  17,  45,  89],
        [173,  35,  16,  12,  86, 109,  67],
        [ 20, 138,   8, 158, 140, 146,  93],
    

In [ ]:
np.random.seed(100)
x3=np.random.randint(200, size=(2,4,2,2,3)) #one dimensional array
x3

array([[[[[  8,  24,  67],
          [103,  87,  79]],

         [[176, 138,  94],
          [180,  98,  53]]],


        [[[ 66,  14,  34],
          [ 24, 143, 107]],

         [[ 60,  58, 144],
          [137,  93,  86]]],


        [[[130, 155, 108],
          [132, 159, 129]],

         [[141, 100,   4],
          [ 91, 187,  67]]],


        [[[135,  49, 175],
          [193,  61,  14]],

         [[183, 199,  80],
          [  2, 121, 105]]]],



       [[[[147,  63, 181],
          [ 27,  56, 113]],

         [[158, 176,  47],
          [167, 109,  38]]],


        [[[172,  18, 192],
          [184, 162, 181]],

         [[ 17,  72,  13],
          [106,  30,  17]]],


        [[[ 53,  68, 178],
          [ 91, 181,  78]],

         [[  0,  13, 185],
          [106, 131,  70]]],


        [[[131, 138, 188],
          [131, 105, 176]],

         [[180,  43,  36],
          [  5,  71,  38]]]]])

In [ ]:
np.random.seed(100)
x4=np.random.randint(200, size=(3,2,1)) #one dimensional array
x4

array([[[  8],
        [ 24]],

       [[ 67],
        [103]],

       [[ 87],
        [ 79]]])

In [ ]:
np.random.seed(100)
x5=np.random.randint(200, size=(4,3,2,1)) #one dimensional array
x5

array([[[[  8],
         [ 24]],

        [[ 67],
         [103]],

        [[ 87],
         [ 79]]],


       [[[176],
         [138]],

        [[ 94],
         [180]],

        [[ 98],
         [ 53]]],


       [[[ 66],
         [ 14]],

        [[ 34],
         [ 24]],

        [[143],
         [107]]],


       [[[ 60],
         [ 58]],

        [[144],
         [137]],

        [[ 93],
         [ 86]]]])

In [ ]:
x5.shape

(4, 3, 2, 1)

In [ ]:
x5.ndim

4

In [ ]:
x5.size

24

In [ ]:
x5.nbytes

192

In [ ]:
#Item Size (give the nbytes value)
x5.itemsize

8