<a href="https://colab.research.google.com/github/KedarSJadhav/MSC_Sem-1_FDS/blob/main/FDS_Lab_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello Word")

Hello Word


**Declare variable and assign value**

In [2]:
a=1

In [3]:
a

1

**Multiple values print**

In [4]:
x=2
y=3
z=4

In [5]:
print(x,y,z)

2 3 4


**Formatted output**

In [12]:
print('Value of x = ' + str(x), ',','Value of y = ' + str(y), ',' ,'Value of z = ' + str(z))

Value of x = 2 , Value of y = 3 , Value of z = 4


**Get type of Variable**

In [22]:
i=5
s="Test"
f=1.23456

In [20]:
type(i)

int

In [21]:
type(s)

str

In [18]:
type(f)

float

$y=x^2$

**List**

In [33]:
a=[1,2,3]

In [34]:
a

[1, 2, 3]

In [35]:
type(a)

list

In [36]:
b=[4,5,6]

In [37]:
b

[4, 5, 6]

In [38]:
c=[]
for i in range(len(a)):
  c.append(a[i]*b[i])

In [39]:
c

[4, 10, 18]

In [40]:
c=[]
for i in range(len(a)):
  c.append(a[i]+b[i])

In [41]:
c

[5, 7, 9]

In [46]:
import time
print("Sleeping")
time.sleep(30)
print("Done sleeping")

Sleeping
Done sleeping


In [52]:
import numpy as np

In [44]:
time.sleep(30)

In [45]:
print("Done sleeping")

Done sleeping


**Using Array**

In [55]:
a=np.arange(15).reshape(3,5)

In [56]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [57]:
a.shape

(3, 5)

In [58]:
a.ndim

2

In [59]:
a.dtype

dtype('int64')

In [62]:
a.dtype.name

'int64'

In [63]:
a.itemsize

8

In [64]:
a.size

15

In [65]:
type(a)

numpy.ndarray

In [67]:
b=np.array([21,22,23])

In [68]:
b

array([21, 22, 23])

In [75]:
c=np.array([[31,32,33],[41,42,43]])

In [76]:
c

array([[31, 32, 33],
       [41, 42, 43]])

In [79]:
d=c.reshape(3,2)
d

array([[31, 32],
       [33, 41],
       [42, 43]])

**Example of Char**

In [89]:
arr=np.array([["One","Two","Three","Four","Five"],["Six","Seven","Eight","Nine","Ten"]])

In [90]:
reshape_arr = arr.reshape(2,5)

In [91]:
reshape_arr

array([['One', 'Two', 'Three', 'Four', 'Five'],
       ['Six', 'Seven', 'Eight', 'Nine', 'Ten']], dtype='<U5')